FROM python:3.9-alpine

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

ENV VERSION=1.3.0
ENV LAST_UPDATE=2023-10-06

COPY ./web /code/web

CMD ["gunicorn", "web.wsgi:app", "--bind", "0.0.0.0:80"]
