FROM python:3.9-alpine

WORKDIR /code

COPY ./requirements.parser.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./parser /code/parser

CMD ["python", "parser/parser_server.py"]
